[project]
name = "esxifree_guest"
version = "0.1.0"
description = "Add a short description here"
authors = ["xiaoyao9184 <6614349+xiaoyao9184@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"

[pypi-dependencies]
paramiko = { version = "==2.8.1" }
pyyaml = { version = "==6.0.1" }
xmltodict = { version = "==0.13.0" }
